### ISSUE TITLE
"appears scrambled or malformed" warning if not in ascending order?

### ISSUE THREAD

**Issue by bbbradsmith** [Alcaro/Flips#13]
I was getting the error "The patch was applied, but appears scrambled or malformed." for an IPS patch that was otherwise being correctly applied and could not understand why.

After building and debugging flips, I discovered that this was caused by the the chunks in the file not appearing in ascending order of address.

Is it possible to make this error more descriptive of which "scrambled or malformed" condition it's giving a warning about? There appear to be at least 3 different conditions that can give this same message.

.

I can see how it's a useful warning if you're expecting your own tool to always generate it in that order, but it doesn't appear to be part of any definition of the file format I could find, so I was very confused about why an IPS I was generating that appeared to obey the format was giving an error in your tool. Was even trying to eliminate chunks one by one to see which one was the cause, but that just led to more confusion since this error isn't due to any specific chunk, but their collective arrangement.

(Otherwise thanks for making a good replacement for LunarIPS. It's very handy to have.)

**Comment by Alcaro** [comment]
I don't think the format is defined anywhere at all, I mostly made things up and matched Lunar IPS.

I couldn't think of any sensible creation algorithm that yields unsorted chunks, so I deemed 'corrupt file' the most likely cause and added that warning. If you've found something I couldn't think of, explain your algorithm and I'll drop it.

**Comment by Alcaro** [comment]
That counts as a valid reason for having unsorted data. Personally I'd use another format for manually generated patches (preferably one that supports comments), but I have little if any right to demand others do that. Or if you edit them in a commentable format, you could add a sorting step to the converter, but figuring out that Flips wants that is indeed quite obscure.

Corrupt patches probably either corrupt a length and desync the EOF, or corrupt data that can't be detected, anyways. Corrupting an address only is rare. And file corruption itself isn't a relevant concept anymore, either.

Obvious follow up question: How about old Flips versions, like [this one](https://www.smwcentral.net/?p=section&a=details&id=11474)? The obvious solution would be submitting an update, I left Windows a while ago, so that's kinda tricky.

**Comment by bbbradsmith** [comment]
This is a Windows build I made with the latest changes.
https://www.dropbox.com/s/xc01tz6fi87tzbr/flips_7856875.zip?dl=0
