### ISSUE TITLE
Can't Create IPS for 16 MB Files

### ISSUE THREAD

**Issue by Blade2187** [Alcaro/Flips#17]
As per title, with input and output files that are exactly 16 MB and using the IPS format, I get the error:

`The IPS format does not support files larger than 16MB.`

While this is true (to my knowledge), there should be no issue supporting files that are exactly 16 MB. The offending check is presumably [this](https://github.com/Alcaro/Flips/blob/242a0bc9acf6830c5480f3411d6dea303b92116c/libips.cpp#L202) or the following line, but I'm not clear why those checks would trigger -- does filemap add 1 byte to the length somewhere along the line?

Thanks.

**Comment by Alcaro** [comment]
Can't reproduce, it creates patches just file on 16777216-byte files.

However, Flips did have such a bug in 1.31, and I haven't made a release since then. Perhaps that's the issue you're encountering? If so, feel free to borrow this binary: https://floating.muncher.se/temp/flipsmp.exe

(it's actually possible to make an IPS for files up to 16MB plus 64KB minus 2, but Flips rejects anything beyond exactly 16M. Such big files are most likely better off as BPS.)

**Comment by Blade2187** [comment]
Confirmed the new version fixes the issue; had assumed the binary I had on hand (1.31) was up to date. Thanks!
