### ISSUE TITLE
Feature Request: add support to prepend 512b before applying IPS patches

### ISSUE THREAD

**Issue by pseiler** [Alcaro/Flips#24]
Unfortunately flips doesn't support prepending the 512b header for applying IPS patches from romhacking.com with headers.
IPS patches without headers work fine. Thank you for you work. I appreciate it very much since it compiles for several plattforms such as linux.

**Comment by Alcaro** [comment]
Long-term, the correct solution to that issue is telling the site admins to replace all IPSes with BPS, which clearly records which input ROM it expects and allows Flips to automatically handle headers.

Short-term, simply apply it to a headered ROM.

I doubt it's worth 

IPS patches with headers work fine if you apply them to headered ROMs.

Long-term, the correct solution is 



Alternatively, the easy way out is simply applying the headered IPS to a headered ROM.


IPS patches with headers work fine if the source ROM is headered.


The best solution I can see is simply using headered ROMs with headered IPSes, ideally combined with telling the IPS distributors to stop that and convert them to BPS.

The correct fix is simply applying the headered IPS to a headered ROM.

Actually, the real correct solution 

Nor can I think of any way to ask the user what to do without being annoying. Most users 

All solutions either redesign the entire UI from scratch, ask questions some users can't answer, or require way too many steps.

being way too much asking questions some users can't answer, redesigning the entire UI from scratch (UI changes tend to be somewhat impopular), or ad


Adding another step to the Apply Patch button would work for some users, but others [wouldn't understand the question](https://devblogs.microsoft.com/oldnewthing/20040426-00/?p=39643). Asking whether to ask is pretty common (usually called 'advanced settings'), but with Flips' dialog sequence interface, there's no good place to put such a thing. (Flips has a Settings panel, but it's so far from Apply Patch it doesn't qualify as good.)

I could ignore that and make it CLI-only (there are a couple of CLI-only options already), but I can't think of a good name. --add-header adds a header to either the patch or the ROM - which one? And --add-header-to-patch is annoyingly long.

Instead, the correct solution is telling the site admins to replace all IPSes with BPS. BPS clearly records which input ROM it expects, allowing Flips to reliably know how much header to add or remove.

Alternatively, the easy way out is simply applying the headered IPS to a headered ROM.

The correct solution



Which means the user must provide this information, and I don't see any good way to do that.

With Flips' dialog sequence GUI, there's no good place to ask that question. If Flips had been [a form-based GUI like beat](https://pbs.twimg.com/media/EEcNTlQUUAA_62v.png), I could add an Advanced dropdown, but in its current state, such questions would probably [confuse users more than it'd help](https://devblogs.microsoft.com/oldnewthing/20040426-00/?p=39643).

I'd also need to expose that feature in the CLI, but I can't find a good name. 

Finally, the IPS header mess is why I created Flips in the first place. I wanted to get rid of IPS from the SMW Central hacks section, and replace them with BPS (which clearly records which input ROM it expects, allowing Flips to seamlessly operate on headered and unheadered ROMs alike). I believe that is the correct solution here too.

Alternatively, simply apply

**Comment by Alcaro** [comment]
Long-term, the correct solution to that issue is telling the site admins to replace all IPSes with BPS, which clearly records which input ROM it expects and allows Flips to automatically handle headers.

Short-term, simply apply it to a headered ROM. I doubt adding another way to handle headered IPSes is worth the effort.

(ignore the double mail, I accidentally hit ctrl-c and enter simultaneously.)

**Comment by pseiler** [comment]
I thought something like this. But thank you for your answer. romhacking.net both provides headered and non-headered ips patches. headered ones seems like a legacy. Newer hacks are mostly non-headered ips or bps files. Thank you very much. For all headered ips patches I use the web patching utility which supports applying the 512b header before patching.
URL: https://www.romhacking.net/patch/
