### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by Vaporeon** [Alcaro/Flips#38]
I read the comment added in 1f14a54dee90a761a0a0be7917a6c203cee94d4d, however I maintain a package on the AUR and have to name it something, since the current package is the old 1.31 release.
Do you mind tagging 1.40 anyway, or should I just make something up and have it build the latest commit?

**Comment by Alcaro** [comment]
There is no 1.40.

I had a checklist of things I want to do before I can call it 1.40, rather than 1.40-pre aka halfway to 1.40. Since the checklist is not complete, there is no commit I can call 1.40. There are 123 commits, so if you need to call it anything, call it version 123.

Versioning is hard. Every versioning scheme I can think of yields weird results for near-dead projects like this one.
