### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by vector-man** [Alcaro/Flips#39]
Hey there. Cool library/program. I'm the coder of LibIPS.NET, which is based on the older, LGPL v3 version of your code (before you changed the license.) I'm wondering if I can update my library to your latest libips version, without changing the library to GPL v3? There were some bugs in the order release that your fixed, but I can't fix them in my library without changing my license.

**Comment by Alcaro** [comment]
You're very welcome to recreate whatever bugfixes you want if you don't copy my implementation, or if there's only one real way to fix that bug, my patches fail the threshold of originality and are not covered by copyright.

If that's not reassuring enough, I haven't done anything significant in libips.{h,cpp} since its initial release, so sure, feel free to copy those fixes. It's mostly libbps-suf.cpp I want to keep GPL'd.
