### ISSUE TITLE
Add .md to the "most common filetypes"

### ISSUE THREAD

**Issue by cheatfreak47** [Alcaro/Flips#6]
*.md is what No-Intro uses, so it's extremely common as well
thanks

**Comment by Alcaro** [comment]
Sure, why not

**Comment by cheatfreak47** [comment]
Wow, you're rather prompt. 
Thanks for the addition. I was also going to suggest publishing releases in the GitHub releases section as well, but that's up to you obviously. 

Thanks for the addition.

**Comment by Alcaro** [comment]
Releases are published [at SMW Central](https://www.smwcentral.net/?p=section&a=details&id=11474).

There hasn't been a release since I created this repo, so technically I do publish all releases that exist.

I don't really like the idea of adding additional steps to the release process, but perhaps it's worth it. If I remember it when it's time to release the next one.
