### ISSUE TITLE
[Question] Why can't you provide any pre-built binaries for the latest version?

### ISSUE THREAD

**Issue by Zachary-Rude** [Alcaro/Flips#68]
Title says it. I just want to know why you _can't_ provide **any** pre-built binaries for the **latest** release of Flips? For some reason, the _only_ pre-built Flips binary that you have **officially** provided is a little outdated. Why not update that binary on SMWCentral to the latest version, or even put some pre-built Flips binaries on this repository's Releases section?

**Comment by Alcaro** [comment]
Because I'm too lazy to submit binaries for every commit. I don't have anywhere to submit them either, I left SMW Central long ago.

I can't submit binaries for some randomly chosen commits either, I don't want to bless any particular commit as more of a release than any other.

...maybe I should set up some CI system that automatically create binaries for everything. Current CI verifies that it can build, but then it discards the binaries, because they're built with certain optimizations disabled. I don't want to distribute anything slower than 1.31.

...or maybe I'm too lazy for that too.

**Comment by Zachary-Rude** [comment]
> Because I'm too lazy to submit binaries for every commit. I don't have anywhere to submit them either, I left SMW Central long ago.
> 
> I can't submit binaries for some randomly chosen commits either, I don't want to bless any particular commit as more of a release than any other.
> 
> ...maybe I should set up some CI system that automatically create binaries for everything. Current CI verifies that it can build, but then it discards the binaries, because they're built with certain optimizations disabled. I don't want to distribute anything slower than 1.31.
> 
> ...or maybe I'm too lazy for that too.

thanks for letting me know! setting up a CI system that automatically creates binaries would be a great idea! if you ever decide to do that, you should probably submit them to this repository's Releases page, since that's something you can do here on github! i'll close the issue now!
