### ISSUE TITLE
Qt for cross-platform GUI?

### ISSUE THREAD

**Issue by rmenessec** [Alcaro/Flips#8]
I did notice that the Flips README.md specified that you're not interested in using Qt. I'm tentatively opening a new issue because you also mentioned that you don't have the right hardware to provide a GUI for OSX.

I admit, my own experience developing against Qt is limited and a bit dated; however, based on that experience, it seems like it's relatively easy to create decent, simple UIs with Qt. Also, while I also do not have (official) hardware on which to run OSX, I was under the impression that clean C/C++ developed against the Qt SDK should normally cross-compile on OSX without much hassle.

Since I don't need Flips to run on OSX, I'm not too concerned about OSX in particular; however, wouldn't it make sense to adopt Qt at some point in order to provide a reasonable cross-platform GUI for Flips? Nearly all the (not-Java) cross-platform projects (including commercial ones) that I've seen target Qt so they can create one GUI and use it everywhere. (The rest are using wxWidgets, or else they're Gimp...)

The last time I did have some access to official OSX-running hardware, Apple Xcode was free-as-in-beer, like Microsoft has finally made Visual Studio, and I ended up using it (Xcode) a fair amount to compile code from various F/OSS projects, including some GUI apps, all of which used Qt.

I understand if it's still too much hassle at this point.

**Comment by Alcaro** [comment]
Your question assumes I want to provide a OSX GUI, rather than telling people to use MultiPatch and Wine.

But yes, the readme does imply that. Fixed.

Using Qt to work around my lack of OSX machines is a good idea in theory, but in practice:
- While the C++ code can be shared, it would require some platform-specific Makefile additions, which I can't test
- I've heard that Qt doesn't look perfectly like native OSX programs, and that OSX users are super picky about everything looking native
- According to a quick google, GTK already works on OSX; probably looks worse than Qt, but for such a simple program, I doubt the difference is noticable
- It would require a fair amount of effort that I have little or no motivation for

Therefore, no, not doing that.

(I'm also getting a vague feeling that you're suggesting using Qt instead of GTK, rather than supporting both. Flips has three different frontends already (GTK, Win32, pure CLI), adding a fourth one wouldn't be a problem.)

**Comment by rmenessec** [comment]
I was suggesting a single GUI, yes.

I don't use OSX enough to say whether Qt apps look **perfectly** native as of Qt 5-current.

The majority of Qt 5 Windows apps I've used look and feel perfectly native relative to Windows desktop. (Not even going to comment on the Windows 8+ looks, plural.)

I apologize if I've worn out your patience. I'm happy sticking to Flips on the Linux command line, personally. Suggestion withdrawn.

**Comment by Alcaro** [comment]
Flips on Windows is a single 100KB file that doesn't need any non-system DLLs (not even those MSVC redists), and I like it that way. A mandatory Qt dependency would add several megabytes.

Perhaps Qt 5 does look perfect on OSX, all I know is Qt 4 doesn't.
